# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photon_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_photons(object):
    def setupUi(self, photons):
        photons.setObjectName("photons")
        photons.resize(1208, 828)
        self.centralwidget = QtWidgets.QWidget(photons)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.connectionBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.connectionBox.setFont(font)
        self.connectionBox.setObjectName("connectionBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.connectionBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.id800_led = QtWidgets.QLabel(self.connectionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id800_led.sizePolicy().hasHeightForWidth())
        self.id800_led.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.id800_led.setFont(font)
        self.id800_led.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.id800_led.setText("")
        self.id800_led.setPixmap(QtGui.QPixmap("../../gui/icons/led-red-on.png"))
        self.id800_led.setScaledContents(True)
        self.id800_led.setObjectName("id800_led")
        self.horizontalLayout_4.addWidget(self.id800_led)
        self.id800_label = QtWidgets.QLabel(self.connectionBox)
        self.id800_label.setObjectName("id800_label")
        self.horizontalLayout_4.addWidget(self.id800_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labjack_led = QtWidgets.QLabel(self.connectionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labjack_led.sizePolicy().hasHeightForWidth())
        self.labjack_led.setSizePolicy(sizePolicy)
        self.labjack_led.setMinimumSize(QtCore.QSize(21, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labjack_led.setFont(font)
        self.labjack_led.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labjack_led.setText("")
        self.labjack_led.setPixmap(QtGui.QPixmap("../../gui/icons/led-red-on.png"))
        self.labjack_led.setScaledContents(True)
        self.labjack_led.setObjectName("labjack_led")
        self.horizontalLayout_3.addWidget(self.labjack_led)
        self.labjack_label = QtWidgets.QLabel(self.connectionBox)
        self.labjack_label.setObjectName("labjack_label")
        self.horizontalLayout_3.addWidget(self.labjack_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addWidget(self.connectionBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.corrida_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.corrida_label.setFont(font)
        self.corrida_label.setObjectName("corrida_label")
        self.horizontalLayout.addWidget(self.corrida_label)
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.progressbar.setPalette(palette)
        self.progressbar.setMaximum(1000)
        self.progressbar.setProperty("value", 1)
        self.progressbar.setTextVisible(False)
        self.progressbar.setObjectName("progressbar")
        self.horizontalLayout.addWidget(self.progressbar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exp_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp_label.sizePolicy().hasHeightForWidth())
        self.exp_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.exp_label.setFont(font)
        self.exp_label.setObjectName("exp_label")
        self.horizontalLayout_2.addWidget(self.exp_label)
        self.save_separator = QtWidgets.QFrame(self.centralwidget)
        self.save_separator.setFrameShape(QtWidgets.QFrame.VLine)
        self.save_separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.save_separator.setObjectName("save_separator")
        self.horizontalLayout_2.addWidget(self.save_separator)
        self.filename = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.filename.setFont(font)
        self.filename.setObjectName("filename")
        self.horizontalLayout_2.addWidget(self.filename)
        self.experiment_separator = QtWidgets.QFrame(self.centralwidget)
        self.experiment_separator.setFrameShape(QtWidgets.QFrame.VLine)
        self.experiment_separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.experiment_separator.setObjectName("experiment_separator")
        self.horizontalLayout_2.addWidget(self.experiment_separator)
        self.counter_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.counter_label.setFont(font)
        self.counter_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.counter_label.setObjectName("counter_label")
        self.horizontalLayout_2.addWidget(self.counter_label)
        self.counter_currentval = QtWidgets.QLCDNumber(self.centralwidget)
        self.counter_currentval.setMinimumSize(QtCore.QSize(0, 75))
        self.counter_currentval.setSmallDecimalPoint(False)
        self.counter_currentval.setMode(QtWidgets.QLCDNumber.Dec)
        self.counter_currentval.setObjectName("counter_currentval")
        self.horizontalLayout_2.addWidget(self.counter_currentval)
        self.counter_slash = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter_slash.sizePolicy().hasHeightForWidth())
        self.counter_slash.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.counter_slash.setFont(font)
        self.counter_slash.setObjectName("counter_slash")
        self.horizontalLayout_2.addWidget(self.counter_slash)
        self.counter_finalval = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counter_finalval.sizePolicy().hasHeightForWidth())
        self.counter_finalval.setSizePolicy(sizePolicy)
        self.counter_finalval.setProperty("intValue", 1000)
        self.counter_finalval.setObjectName("counter_finalval")
        self.horizontalLayout_2.addWidget(self.counter_finalval)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.paramsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.paramsBox.setMinimumSize(QtCore.QSize(200, 0))
        self.paramsBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.paramsBox.setFont(font)
        self.paramsBox.setObjectName("paramsBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.paramsBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.paramsList = QtWidgets.QListWidget(self.paramsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramsList.sizePolicy().hasHeightForWidth())
        self.paramsList.setSizePolicy(sizePolicy)
        self.paramsList.setMinimumSize(QtCore.QSize(0, 0))
        self.paramsList.setObjectName("paramsList")
        self.verticalLayout_4.addWidget(self.paramsList)
        self.input50btn = QtWidgets.QRadioButton(self.paramsBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.input50btn.setFont(font)
        self.input50btn.setChecked(True)
        self.input50btn.setObjectName("input50btn")
        self.verticalLayout_4.addWidget(self.input50btn)
        self.input1000btn = QtWidgets.QRadioButton(self.paramsBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.input1000btn.setFont(font)
        self.input1000btn.setObjectName("input1000btn")
        self.verticalLayout_4.addWidget(self.input1000btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.testing = QtWidgets.QGroupBox(self.paramsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testing.sizePolicy().hasHeightForWidth())
        self.testing.setSizePolicy(sizePolicy)
        self.testing.setCheckable(True)
        self.testing.setChecked(False)
        self.testing.setObjectName("testing")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.testing)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(30, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.verticalLayout_5.addItem(spacerItem1)
        self.selftest_check = QtWidgets.QCheckBox(self.testing)
        self.selftest_check.setObjectName("selftest_check")
        self.verticalLayout_5.addWidget(self.selftest_check)
        self.manual_expdur_label = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_expdur_label.sizePolicy().hasHeightForWidth())
        self.manual_expdur_label.setSizePolicy(sizePolicy)
        self.manual_expdur_label.setObjectName("manual_expdur_label")
        self.verticalLayout_5.addWidget(self.manual_expdur_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.manualtime = QtWidgets.QLineEdit(self.testing)
        self.manualtime.setObjectName("manualtime")
        self.horizontalLayout_6.addWidget(self.manualtime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.runButton = QtWidgets.QPushButton(self.testing)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_5.addWidget(self.runButton)
        self.verticalLayout_4.addWidget(self.testing)
        self.horizontalLayout_13.addWidget(self.paramsBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.counts_tab = QtWidgets.QWidget()
        self.counts_tab.setObjectName("counts_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.counts_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timebinning = QtWidgets.QComboBox(self.counts_tab)
        self.timebinning.setObjectName("timebinning")
        self.timebinning.addItem("")
        self.timebinning.addItem("")
        self.timebinning.addItem("")
        self.timebinning.addItem("")
        self.gridLayout_4.addWidget(self.timebinning, 0, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.counts_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.counts_plot = GraphicsLayoutWidget(self.counts_tab)
        self.counts_plot.setObjectName("counts_plot")
        self.gridLayout_4.addWidget(self.counts_plot, 1, 0, 1, 5)
        self.playbackBtn = QtWidgets.QPushButton(self.counts_tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/player_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icons/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playbackBtn.setIcon(icon)
        self.playbackBtn.setCheckable(True)
        self.playbackBtn.setChecked(False)
        self.playbackBtn.setObjectName("playbackBtn")
        self.gridLayout_4.addWidget(self.playbackBtn, 0, 3, 1, 1)
        self.tabWidget.addTab(self.counts_tab, "")
        self.hist_tab = QtWidgets.QWidget()
        self.hist_tab.setObjectName("hist_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.hist_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.hist_plot = PlotWidget(self.hist_tab)
        self.hist_plot.setObjectName("hist_plot")
        self.gridLayout.addWidget(self.hist_plot, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.hist_tab)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.channelAbox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelAbox.sizePolicy().hasHeightForWidth())
        self.channelAbox.setSizePolicy(sizePolicy)
        self.channelAbox.setObjectName("channelAbox")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.channelAbox.addItem("")
        self.horizontalLayout_14.addWidget(self.channelAbox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.channelBbox = QtWidgets.QComboBox(self.groupBox)
        self.channelBbox.setObjectName("channelBbox")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.channelBbox.addItem("")
        self.horizontalLayout_14.addWidget(self.channelBbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.hist_tab, "")
        self.horizontalLayout_13.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        photons.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(photons)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 26))
        self.menubar.setObjectName("menubar")
        photons.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(photons)
        self.statusbar.setObjectName("statusbar")
        photons.setStatusBar(self.statusbar)

        self.retranslateUi(photons)
        self.tabWidget.setCurrentIndex(0)
        self.timebinning.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(photons)

    def retranslateUi(self, photons):
        _translate = QtCore.QCoreApplication.translate
        photons.setWindowTitle(_translate("photons", "photons"))
        self.connectionBox.setTitle(_translate("photons", "Connection"))
        self.id800_label.setText(_translate("photons", "ID800"))
        self.labjack_label.setText(_translate("photons", "LabJack"))
        self.corrida_label.setText(_translate("photons", "Progress"))
        self.progressbar.setFormat(_translate("photons", "%v/%m"))
        self.exp_label.setText(_translate("photons", "Save as"))
        self.filename.setText(_translate("photons", "TextLabel"))
        self.counter_label.setText(_translate("photons", "Experiment"))
        self.counter_slash.setText(_translate("photons", "/"))
        self.paramsBox.setTitle(_translate("photons", "Parameters"))
        self.input50btn.setText(_translate("photons", "50 Ω Input Term."))
        self.input1000btn.setText(_translate("photons", "1000 Ω Input Term."))
        self.testing.setTitle(_translate("photons", "Testing"))
        self.selftest_check.setText(_translate("photons", "Self Test"))
        self.manual_expdur_label.setText(_translate("photons", "Run for (s):"))
        self.manualtime.setText(_translate("photons", "5"))
        self.runButton.setText(_translate("photons", "Run"))
        self.timebinning.setItemText(0, _translate("photons", "30 ms"))
        self.timebinning.setItemText(1, _translate("photons", "50 ms"))
        self.timebinning.setItemText(2, _translate("photons", "100 ms"))
        self.timebinning.setItemText(3, _translate("photons", "200 ms"))
        self.label_2.setText(_translate("photons", "Time bin"))
        self.playbackBtn.setText(_translate("photons", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.counts_tab), _translate("photons", "Counts"))
        self.groupBox.setTitle(_translate("photons", "Not global"))
        self.label.setText(_translate("photons", "Channel A"))
        self.channelAbox.setItemText(0, _translate("photons", "1"))
        self.channelAbox.setItemText(1, _translate("photons", "2"))
        self.channelAbox.setItemText(2, _translate("photons", "3"))
        self.channelAbox.setItemText(3, _translate("photons", "4"))
        self.channelAbox.setItemText(4, _translate("photons", "5"))
        self.channelAbox.setItemText(5, _translate("photons", "6"))
        self.channelAbox.setItemText(6, _translate("photons", "7"))
        self.channelAbox.setItemText(7, _translate("photons", "8"))
        self.label_3.setText(_translate("photons", "Channel B"))
        self.channelBbox.setItemText(0, _translate("photons", "1"))
        self.channelBbox.setItemText(1, _translate("photons", "2"))
        self.channelBbox.setItemText(2, _translate("photons", "3"))
        self.channelBbox.setItemText(3, _translate("photons", "4"))
        self.channelBbox.setItemText(4, _translate("photons", "5"))
        self.channelBbox.setItemText(5, _translate("photons", "6"))
        self.channelBbox.setItemText(6, _translate("photons", "7"))
        self.channelBbox.setItemText(7, _translate("photons", "8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hist_tab), _translate("photons", "Hist"))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget
import resources_rc
